name: nflamously.dev-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy-inflamous-dev:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout repository
        run: "git clone https://github.com/inflamously/nflamously.dev.git"
      - name: Checkout master
        working-directory: app
        run: "git checkout master"
      - name: Install dependencies
        working-directory: app
        run: "npm ci"
#      - name: Run application linter
#        working-directory: app
#        run: "npm run test"
      - name: Run application tests
        working-directory: app
        run: "npm run test"
      - name: Build application
        working-directory: nflamously.dev
        run: "npm run build"
